### ISSUE TITLE
when using make sim, .wdb file ends up in the wrong directory

### ISSUE THREAD

**Issue by joosthooz** [OpenCAPI/oc-accel#139]
When using `make sim` (instead of the python workflow script), the waveform file (wdb) ends up in the wrong directory (not in xsim/latest, but higher in the hierarchy). `./display_traces` then fails because it cannot locate the file.

**Comment by bmesnet** [comment]
Hi @joosthooz. 
Do you run the `make sim `from the oc-accel installation directory or from elsewhere?
If not then you may adapt it for your specific case.
The setup is done in `~/hardware/setup/export_xsim.tcl` then patched by `~/hardware/setup/patch_sim.sh` and then `~/hardware/sim/run_sim` is launched
see [Makefile](https://github.com/OpenCAPI/oc-accel/blob/master/hardware/Makefile#L488-L490)

**Comment by joosthooz** [comment]
I run it from the oc-accel base dir. Are you not able to reproduce? this is my output:
```
...
[SIMULATION........] done  15:07:41 Wed Sep 15 2021
-----------
  Suggested next step: to display waveforms, execute: ./display_traces
jjhoozemans@tud211698:~/workspaces/openCAPI/oc-accel> ./display_traces 
ERROR: Can't access WDB file "xsim/latest/top.wdb". Please check that the file exists and you have read permission.
```
Is it possible that the python script changes the working dir to the generated `latest` directory and the Makefile and `run_sim` script uses `hardware/sim/xsim`  as wdir?

**Comment by bmesnet** [comment]
ok . I have just reproduced it. Let us investigate it . 
We need to see if this could be due to a recent change we applied. 
Thanks

**Comment by bmesnet** [comment]
It is indeed due to a change we did in `run_sim `to support the latest Vivado release (2020.1 and later). We are working on a fix. We can provide you a patch if you are running a vivado release lower than 2020.1

**Comment by bmesnet** [comment]
HI @joosthooz 
This issue is now corrected. Thanks for raising it. I'll let you close the case if you are ok with it

**Comment by joosthooz** [comment]
Thanks Bruno 👍
