### ISSUE TITLE
HLS memcopy example with HBM fails 

### ISSUE THREAD

**Issue by singagan** [OpenCAPI/oc-accel#41]
Hi, 
I have been trying to run HLS memcpy example with "Enable HBM" through the configuration menu.
However, "make sim" fails with ERROR: [Vivado 12-172] File or Directory '~/oc-accel/hardware/oc-bip/board_support_packages/ad9h7/xdc/snap_hbm_timing.xdc' does not exist

Is it just a missing file or HBM support is still not available?

Vivado version: 2018.3

Thanks.

**Comment by bmesnet** [comment]
Hi @singagan 
Thanks for notifying us. Indeed it is not needed for a simulation. It has already been corrected in master branch. New code to fully support 9H7 should be released in master branch shortly.
Let us know if this answers your question.

**Comment by bmesnet** [comment]
hi @singagan 
Thanks for notifying us. Indeed it is not needed for a simulation. 
New code to fully support 9H7 should be released in master branch shortly.
As a temporary circumvention, you can comment the [lines ](https://github.com/OpenCAPI/oc-accel/blob/master/hardware/setup/create_framework.tcl#L269-L271)calling these xdc files
Thanks for your understanding

**Comment by singagan** [comment]
Hi @bmesnet,
I was able to successfully compile HBM memcpy example.

Thank you very much.
