### ISSUE TITLE
Change word_t's elements in hls_helloworld action

### ISSUE THREAD

**Issue by githubhahaha** [OpenCAPI/oc-accel#59]
The `word_t` defined in `action_uppercase.H` was an array of `char`  and the length was 512bits. Now I would like to transmit numbers in 16bits, so I modified the code as follow:
```
typedef char word_t[BPERDW];
```
to
```
typedef short word_t[BPERDW/2];
```
Then I changed the C code depended on this.

When I compiled the action, it gave an error said:

`Interface parameter 'din_gmem.V' must have the same bitwitdth with the local buffer.`

I suppose when I use `char`, a `word_t` can contian 64 char to fill the interface in 512 bitwitdh, but 32*16`(short)` also can fill the 512 bitwidth. I dont know my usage is right. 

Vivado version: 2018.3.1

Thanks.

**Comment by luyong6** [comment]
Hi @githubhahaha 

```
memcpy((char*) text, din_gmem + i_idx, BPERDW);
```
The HLS build-in function memcpy may have its own limitations and doesn't support all kinds of type casting. 

If you want to fill a vector of "short", the reliable way is to write each element explicitly: 
```
snap_membus_t buffer1[1];
memcpy(buffer1, din_gmem + i_idx, BPERDW);
```
```
for  (i = 0; i < 32; i++)
    vector[i] = buffer1[0](i*16+15, i*16);
```
Please note you may still need to adjust the endian in above code segment.

**Comment by bmesnet** [comment]
Hi @githubhahaha
Can we consider this question as answered? If yes, can we close the issue? Thanks

**Comment by bmesnet** [comment]
Understanding that question is answered. Closing the issue. Please reopen it any other question
