### ISSUE TITLE
Card lost after oc-reset if data transfers were done previously.

### ISSUE THREAD

**Issue by bmesnet** [OpenCAPI/oc-accel#82]
If, after a data transfer, an oc-reset is performed, then server hits the following error
`[  401.278714553,3] NPU[0] FIR2 = 0x0200000000000000 (mask 0xffffeffffffdbfff => 0x0000000000000000)`
corresponding to 
`bit 6: OTL_RXI_ACTAG_INV: OTL RX acTag specified in the command points to an invalid entry.`

Action and MMIO logics are not involved (soft_reset doesn't recreate the issue)
Issue only encountered after an oc-reset and never after a power-on.
After oc-reset, MMIO stay accessible but first data access hits the issue.
Once the issue hit, registers are read as -1.

This issue is related to #48 changes. Investigation continues but bridge logic changes are highly suspected.
The issue seems related to the use of old pasid/actags not reset.

**Comment by bmesnet** [comment]
Just resetting the valid bit of the RAM made the trick.

**Comment by bmesnet** [comment]
Still finalizing regression tests before merging code to master. Will close the bug when code is merged.

**Comment by acastellane** [comment]
test ok so far, thanks for solving.
